name: Probar sacatangas

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar sacatangas
        env:
          HAXBALL_ROOM_LINK: ${{ secrets.HAXBALL_ROOM_LINK }}
        run: npm start
